export const EVENT_TYPES = {
  SSH: 'SSH',
  LOGIN: 'LOGIN',
  PRIVILEGE_CHANGE: 'PRIVILEGE_CHANGE',
  DATABASE_ACCESS: 'DATABASE_ACCESS',
  PORT_SCAN: 'PORT_SCAN',
  LATERAL_MOVEMENT: 'LATERAL_MOVEMENT',
  DATA_EXFILTRATION: 'DATA_EXFILTRATION',
  DNS_QUERY: 'DNS_QUERY',
};

export const EVENT_STATUS = {
  ALLOWED: 'Allowed',
  FAILED: 'Failed',
  SUCCESS: 'Success',
  BLOCKED: 'Blocked',
  SUSPICIOUS: 'Suspicious',
};
