export const SEVERITY = {
  CRITICAL: 'CRITICAL',
  HIGH: 'HIGH',
  MEDIUM: 'MEDIUM',
  LOW: 'LOW',
  INFO: 'INFO',
};

export const SEVERITY_CONFIG = {
  CRITICAL: {
    label: 'Critical',
    color: '#ef4444',
    bgColor: 'bg-red-500/10',
    borderColor: 'border-red-500/40',
    textColor: 'text-red-400',
    glowClass: 'glow-critical',
    dotColor: 'bg-red-500',
    badgeClass: 'bg-red-950/80 text-red-400 border border-red-500/50',
    priority: 5,
  },
  HIGH: {
    label: 'High',
    color: '#f97316',
    bgColor: 'bg-orange-500/10',
    borderColor: 'border-orange-500/40',
    textColor: 'text-orange-400',
    glowClass: 'glow-warning',
    dotColor: 'bg-orange-500',
    badgeClass: 'bg-orange-950/80 text-orange-400 border border-orange-500/50',
    priority: 4,
  },
  MEDIUM: {
    label: 'Medium',
    color: '#eab308',
    bgColor: 'bg-yellow-500/10',
    borderColor: 'border-yellow-500/40',
    textColor: 'text-yellow-400',
    glowClass: 'glow-warning',
    dotColor: 'bg-yellow-500',
    badgeClass: 'bg-yellow-950/80 text-yellow-400 border border-yellow-500/50',
    priority: 3,
  },
  LOW: {
    label: 'Low',
    color: '#3b82f6',
    bgColor: 'bg-blue-500/10',
    borderColor: 'border-blue-500/40',
    textColor: 'text-blue-400',
    glowClass: 'glow-cyan',
    dotColor: 'bg-blue-500',
    badgeClass: 'bg-blue-950/80 text-blue-400 border border-blue-500/50',
    priority: 2,
  },
  INFO: {
    label: 'Info',
    color: '#10b981',
    bgColor: 'bg-emerald-500/10',
    borderColor: 'border-emerald-500/40',
    textColor: 'text-emerald-400',
    glowClass: '',
    dotColor: 'bg-emerald-500',
    badgeClass: 'bg-emerald-950/80 text-emerald-400 border border-emerald-500/50',
    priority: 1,
  },
};
